(part "74439346150"
    (packageRef "74439346150")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Manufacturer_Name" "Wurth Elektronik")
    (property "Manufacturer_Part_Number" "74439346150")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "WE-XHMI SMT Power Inductor")
    (property "Datasheet_Link" "https://www.we-online.com/katalog/datasheet/74439346150.pdf")
    (property "symbolName1" "74439346150")
)
