(part "ABM10AIG-40_000MHZ-7-J1Z-T"
    (packageRef "ABM10AIG")
    (interface
        (port "1" (symbPinId 1) (portName "XTAL_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "XTAL_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Manufacturer_Name" "ABRACON")
    (property "Manufacturer_Part_Number" "ABM10AIG-40.000MHZ-7-J1Z-T")
    (property "Mouser_Part_Number" "815-M10AIG-40-7J1ZT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ABRACON/ABM10AIG-40.000MHZ-7-J1Z-T?qs=uwxL4vQweFM9TX6A4vx2XA%3D%3D")
    (property "Arrow_Part_Number" "ABM10AIG-40.000MHZ-7-J1Z-T")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/abm10aig-40.000mhz-7-j1z-t/abracon")
    (property "Description" "Automotive & Industrial Grade Ceramic Base SMD Crystal")
    (property "Datasheet_Link" "https://abracon.com/AIGcrystals/ABM10AIG.pdf")
    (property "symbolName1" "ABM10AIG-40_000MHZ-7-J1Z-T")
)
