SamacSys ECAD Model
291186/373961/2.50/4/3/Connector

DESIGNSPARK_INTERMEDIATE_ASCII

(asciiHeader
	(fileUnits MM)
)
(library Library_1
	(padStyleDef "c140_h90"
		(holeDiam 0.9)
		(padShape (layerNumRef 1) (padShapeType Ellipse)  (shapeWidth 1.400) (shapeHeight 1.400))
		(padShape (layerNumRef 16) (padShapeType Ellipse)  (shapeWidth 1.400) (shapeHeight 1.400))
	)
	(padStyleDef "s140_h90"
		(holeDiam 0.9)
		(padShape (layerNumRef 1) (padShapeType Rect)  (shapeWidth 1.400) (shapeHeight 1.400))
		(padShape (layerNumRef 16) (padShapeType Rect)  (shapeWidth 1.400) (shapeHeight 1.400))
	)
	(textStyleDef "Default"
		(font
			(fontType Stroke)
			(fontFace "Helvetica")
			(fontHeight 50 mils)
			(strokeWidth 5 mils)
		)
	)
	(patternDef "S4BXHALFSN" (originalName "S4BXHALFSN")
		(multiLayer
			(pad (padNum 1) (padStyleRef s140_h90) (pt 0.000, 0.000) (rotation 90))
			(pad (padNum 2) (padStyleRef c140_h90) (pt -2.500, 0.000) (rotation 90))
			(pad (padNum 3) (padStyleRef c140_h90) (pt -5.000, 0.000) (rotation 90))
			(pad (padNum 4) (padStyleRef c140_h90) (pt -7.500, 0.000) (rotation 90))
		)
		(layerContents (layerNumRef 18)
			(attr "RefDes" "RefDes" (pt -3.750, 3.450) (textStyleRef "Default") (isVisible True))
		)
		(layerContents (layerNumRef 28)
			(line (pt 2.45 -2.3) (pt -9.95 -2.3) (width 0.1))
		)
		(layerContents (layerNumRef 28)
			(line (pt -9.95 -2.3) (pt -9.95 9.2) (width 0.1))
		)
		(layerContents (layerNumRef 28)
			(line (pt -9.95 9.2) (pt 2.45 9.2) (width 0.1))
		)
		(layerContents (layerNumRef 28)
			(line (pt 2.45 9.2) (pt 2.45 -2.3) (width 0.1))
		)
		(layerContents (layerNumRef 30)
			(line (pt 3.45 10.2) (pt -10.95 10.2) (width 0.1))
		)
		(layerContents (layerNumRef 30)
			(line (pt -10.95 10.2) (pt -10.95 -3.3) (width 0.1))
		)
		(layerContents (layerNumRef 30)
			(line (pt -10.95 -3.3) (pt 3.45 -3.3) (width 0.1))
		)
		(layerContents (layerNumRef 30)
			(line (pt 3.45 -3.3) (pt 3.45 10.2) (width 0.1))
		)
		(layerContents (layerNumRef 18)
			(line (pt 2.45 9.2) (pt -9.95 9.2) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt -9.95 9.2) (pt -9.95 -2.3) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt -9.95 -2.3) (pt 2.45 -2.3) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt 2.45 -2.3) (pt 2.45 9.2) (width 0.2))
		)
	)
	(symbolDef "S4B-XH-A_LF__SN_" (originalName "S4B-XH-A_LF__SN_")

		(pin (pinNum 1) (pt 0 mils -300 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -325 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 2) (pt 0 mils -200 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -225 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 3) (pt 0 mils -100 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -125 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 4) (pt 0 mils 0 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -25 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(line (pt 200 mils 100 mils) (pt 600 mils 100 mils) (width 6 mils))
		(line (pt 600 mils 100 mils) (pt 600 mils -400 mils) (width 6 mils))
		(line (pt 600 mils -400 mils) (pt 200 mils -400 mils) (width 6 mils))
		(line (pt 200 mils -400 mils) (pt 200 mils 100 mils) (width 6 mils))
		(attr "RefDes" "RefDes" (pt 650 mils 300 mils) (justify Left) (isVisible True) (textStyleRef "Default"))

	)
	(compDef "S4B-XH-A_LF__SN_" (originalName "S4B-XH-A_LF__SN_") (compHeader (numPins 4) (numParts 1) (refDesPrefix J)
		)
		(compPin "1" (pinName "1") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "2" (pinName "2") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "3" (pinName "3") (partNum 1) (symPinNum 3) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "4" (pinName "4") (partNum 1) (symPinNum 4) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(attachedSymbol (partNum 1) (altType Normal) (symbolName "S4B-XH-A_LF__SN_"))
		(attachedPattern (patternNum 1) (patternName "S4BXHALFSN")
			(numPads 4)
			(padPinMap
				(padNum 1) (compPinRef "1")
				(padNum 2) (compPinRef "2")
				(padNum 3) (compPinRef "3")
				(padNum 4) (compPinRef "4")
			)
		)
		(attr "Manufacturer_Name" "JST (JAPAN SOLDERLESS TERMINALS)")
		(attr "Manufacturer_Part_Number" "S4B-XH-A(LF)(SN)")
		(attr "Mouser Part Number" "N/A")
		(attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/JST-Commercial/S4B-XH-ALFSN?qs=QpmGXVUTftF7eeJ4yg3VYQ%3D%3D")
		(attr "Arrow Part Number" "S4B-XH-A(LF)(SN)")
		(attr "Arrow Price/Stock" "https://www.arrow.com/en/products/s4b-xh-a-lf-sn/jst-manufacturing?utm_currency=USD&region=europe")
		(attr "Description" "XH-2.5mm Header side entry 4 way JST XH Series, Series Number S4B, 2.5mm Pitch 4 Way 1 Row Right Angle PCB Header, Solder Termination, 3A")
		(attr "Datasheet Link" "https://www.mouser.co.uk/ProductDetail/JST-Commercial/S4B-XH-ALFSN?qs=QpmGXVUTftEyAvx%252Br33AyQ%3D%3D&srsltid=AfmBOopXgwHK5vQKy207Eg2VBdixziHXVBrLkW0Mvqq_XGzuQb0VSmKc")
		(attr "Height" "7 mm")
	)

)
