(part "TCAN1046AVDYYRQ1"
    (packageRef "SOP50P326X110-14N")
    (interface
        (port "1" (symbPinId 1) (portName "TXD1") (portType INPUT))
        (port "2" (symbPinId 2) (portName "GND1") (portType GROUND))
        (port "3" (symbPinId 3) (portName "VCC") (portType INOUT))
        (port "4" (symbPinId 4) (portName "RXD1") (portType OUTPUT))
        (port "5" (symbPinId 5) (portName "GND2") (portType GROUND))
        (port "6" (symbPinId 6) (portName "TXD2") (portType INPUT))
        (port "7" (symbPinId 7) (portName "RXD2") (portType OUTPUT))
        (port "8" (symbPinId 8) (portName "STB2") (portType INPUT))
        (port "9" (symbPinId 9) (portName "CANL2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "CANH2") (portType INOUT))
        (port "11" (symbPinId 11) (portName "VIO") (portType POWER))
        (port "12" (symbPinId 12) (portName "CANL1") (portType INOUT))
        (port "13" (symbPinId 13) (portName "CANH1") (portType INOUT))
        (port "14" (symbPinId 14) (portName "STB1") (portType INPUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TCAN1046AVDYYRQ1")
    (property "Mouser_Part_Number" "595-TCAN1046AVDYYRQ1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TCAN1046AVDYYRQ1?qs=doiCPypUmgHWM9fDrxlKTw%3D%3D")
    (property "Arrow_Part_Number" "TCAN1046AVDYYRQ1")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tcan1046avdyyrq1/texas-instruments?utm_currency=USD&region=nac")
    (property "Description" "Dual CAN Transceiver")
    (property "Datasheet_Link" "https://www.ti.com/lit/ds/symlink/tcan1046av-q1.pdf?ts=1705486781922")
    (property "symbolName1" "TCAN1046AVDYYRQ1")
)
