(part "SN65HVD1782QDRQ1"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "R") (portType INOUT))
        (port "2" (symbPinId 2) (portName "RE") (portType INOUT))
        (port "3" (symbPinId 3) (portName "DE") (portType INOUT))
        (port "4" (symbPinId 4) (portName "D") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND") (portType INOUT))
        (port "6" (symbPinId 6) (portName "A") (portType INOUT))
        (port "7" (symbPinId 7) (portName "B") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "SN65HVD1782QDRQ1")
    (property "Mouser_Part_Number" "595-SN65HVD1782QDRQ1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/SN65HVD1782QDRQ1?qs=8%2FmU9qzJpL8mmEwMbjC79g%3D%3D")
    (property "Arrow_Part_Number" "SN65HVD1782QDRQ1")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/sn65hvd1782qdrq1/texas-instruments?region=nac")
    (property "Description" "Automotive Fault-Protected RS-485 Transceivers with 3.3-V to 5-V Operation")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/sn65hvd1782-q1.pdf")
    (property "symbolName1" "SN65HVD1782QDRQ1")
)
