(part "TPS22997RYZR"
    (packageRef "TPS22997RYZR")
    (interface
        (port "1" (symbPinId 1) (portName "VBIAS") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VIN_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VIN_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "PG") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND") (portType INOUT))
        (port "6" (symbPinId 6) (portName "QOD") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VOUT_1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VOUT_2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "CT") (portType INOUT))
        (port "10" (symbPinId 10) (portName "ON") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS22997RYZR")
    (property "Mouser_Part_Number" "595-TPS22997RYZR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS22997RYZR?qs=amGC7iS6iy986RqKkXLlig%3D%3D")
    (property "Arrow_Part_Number" "TPS22997RYZR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tps22997ryzr/texas-instruments?utm_currency=USD&region=nac")
    (property "Description" "TPS22997 5.5-V, 10-A, 4-m On-Resistance Load Switch with Adjustable Rise Time")
    (property "Datasheet_Link" "https://www.ti.com/lit/gpn/tps22997?HQS=ti-null-null-sf-df-pf-sep-wwe&DCM=yes?hkey=EF798316E3902B6ED9A73243A3159BB0")
    (property "symbolName1" "TPS22997RYZR")
)
