(part "SI4497DY-T1-GE3"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "S_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "G") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "D_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "SI4497DY-T1-GE3")
    (property "Mouser_Part_Number" "781-SI4497DY-T1-GE3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Semiconductors/SI4497DY-T1-GE3?qs=WX95TUc1y57nwgYqN479sg%3D%3D")
    (property "Arrow_Part_Number" "SI4497DY-T1-GE3")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/si4497dy-t1-ge3/vishay?utm_currency=USD&region=europe")
    (property "Description" "MOSFET -30V Vds 20V Vgs SO-8")
    (property "Datasheet_Link" "https://www.vishay.com/docs/65748/si4497dy.pdf")
    (property "symbolName1" "SI4497DY-T1-GE3")
)
