(part "G125-MH104M4-04AD000P"
    (packageRef "G125MH104M404AD000P")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "A1" (symbPinId 5) (portName "A1") (portType INOUT))
        (port "A2" (symbPinId 6) (portName "A2") (portType INOUT))
        (port "A3" (symbPinId 7) (portName "A3") (portType INOUT))
        (port "A4" (symbPinId 8) (portName "A4") (portType INOUT))
        (port "MH1" (symbPinId 9) (portName "MH1") (portType INOUT))
        (port "MH2" (symbPinId 10) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Harwin")
    (property "Manufacturer_Part_Number" "G125-MH104M4-04AD000P")
    (property "Mouser_Part_Number" "855-G125MH14M44AD00P")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Harwin/G125-MH104M4-04AD000P?qs=Y0Uzf4wQF3nR%252B22z%252BtmrYQ%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Gecko-MT: 4+4 Pos Plug Right-Angle THT Connector Screw-Lok Board Mount")
    (property "Datasheet_Link" "https://content.harwin.com/m/91a65d72bc24bdea/original/DRG-03150-Technical-Drawing-Datasheet-G125-MH1XXM4-XXAD000P-pdf.pdf")
    (property "symbolName1" "G125-MH104M4-04AD000P")
)
