(part "SS-5D"
    (packageRef "SS5D")
    (interface
        (port "1" (symbPinId 1) (portName "COM") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NO") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "OMRON Electronics")
    (property "Manufacturer_Part_Number" "SS-5D")
    (property "Mouser_Part_Number" "653-SS-5D")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Omron-Electronics/SS-5D/?qs=pWf36BUtxBh%252BlIUjzjOszg%3D%3D")
    (property "Arrow_Part_Number" "SS-5D")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ss5d/omron?region=europe")
    (property "Description" "Subminiature Basic Switch,  125VAC, 5A, SPDT, Pin Plunger, OF:max. 1.47N, PCB Terminal")
    (property "Datasheet_Link" "https://components.omron.com/us-en/sites/components.omron.com.us/files/datasheet_pdf/B032-E1.pdf")
    (property "symbolName1" "SS-5D")
)
